<ul id="nav">
	<li>
		<a>Category&nbsp;1</a>
		<ul>
			<li><a>Sub&nbsp;category&nbsp;1</a></li>
			<li><a>Sub&nbsp;category&nbsp;2</a></li>
			<li><a>Sub&nbsp;category&nbsp;3</a></li>
			<li><a>Sub&nbsp;category&nbsp;4</a></li>
		</ul>
	</li>
	<li>
		<a>Category&nbsp;2</a>
		<ul>
			<li><a>Sub&nbsp;category&nbsp;1</a></li>
			<li><a>Sub&nbsp;category&nbsp;2</a></li>
			<li><a>Sub&nbsp;category&nbsp;3</a></li>
			<li><a>Sub&nbsp;category&nbsp;4</a></li>
		</ul>
	</li>
	<li>
		<a>Category&nbsp;3</a>
		<ul>
			<li><a>Sub&nbsp;category&nbsp;1</a></li>
			<li><a>Sub&nbsp;category&nbsp;2</a></li>
			<li><a>Sub&nbsp;category&nbsp;3</a></li>
			<li><a>Sub&nbsp;category&nbsp;4</a></li>
		</ul>
	</li>
	<li>
		<a>Category&nbsp;4</a>
		<ul>
			<li><a>Sub&nbsp;category&nbsp;1</a></li>
			<li><a>Sub&nbsp;category&nbsp;2</a></li>
			<li><a>Sub&nbsp;category&nbsp;3</a></li>
			<li><a>Sub&nbsp;category&nbsp;4</a></li>
		</ul>
	</li>
	<li>
		<a>Category&nbsp;5</a>
		<ul>
			<li><a>Sub&nbsp;category&nbsp;1</a></li>
			<li><a>Sub&nbsp;category&nbsp;2</a></li>
			<li><a>Sub&nbsp;category&nbsp;3</a></li>
			<li><a>Sub&nbsp;category&nbsp;4</a></li>
		</ul>
	</li>
	<li>
		<a>Category&nbsp;6</a>
		<ul>
			<li><a>Sub&nbsp;category&nbsp;1</a></li>
			<li><a>Sub&nbsp;category&nbsp;2</a></li>
			<li><a>Sub&nbsp;category&nbsp;3</a></li>
			<li><a>Sub&nbsp;category&nbsp;4</a></li>
		</ul>
	</li>
</ul>
