<ul id="nav">
	<li>
		<a>Acer</a>
		<ul>
			<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
	<li>
		<a>Asus</a>
		<ul>
			<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
	<li>
		<a>Apple</a>
		<ul>
			<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
	<li>
		<a>Dell</a>
		<ul>
		<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
	<li>
		<a>Hewlett Packard</a>
		<ul>
			<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
	<li>
		<a>Toshiba</a>
		<ul>
			<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
		<li>
		<a>Samsung</a>
		<ul>
			<li><a>Netbook</a></li>
			<li><a>Notebook</a></li>
			<li><a>Performance</a></li>
			<li><a>Multimedia</a></li>
			<li><a>Gamers</a></li>
		</ul>
	</li>
	<li>
		<a>Accessories</a>
		<ul>
			<li><a>Battery chargers</a></li>
			<li><a>USB Flash Drive</a></li>
			<li><a>Laptop case</a></li>
			<li><a>Printers</a></li>
		</ul>
	</li>
</ul>
